# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'sc-dockerhub'
  imageRepository: 'image-shopping-cart'
  containerRegistry: 'whuera'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  # imagePullSecret: 'aksdevopsacrpd1755e8d5-auth'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
      