name: image-shopping-cart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/chackout@v2
    - name: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-shopping-cart:$(date +%s)
