# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-app-shopping-cart

on:
  push:
    branches:
      - feature/add-error-control
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6b7a59dd49384fe083eb9629abd897fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cf875c5f439f41f9b431f03f74dca927 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6b7a59dd49384fe083eb9629abd897fb }}/whuera/image-shopping-cart:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-app-shopping-cart'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8e87dc8207aa4fbea6e36f59a45a748a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6b7a59dd49384fe083eb9629abd897fb }}/whuera/image-shopping-cart:${{ github.sha }}'